name: triggers

on:
  push: 
      branches: 
          - 'main'
          - 'aprendiendo-github-actions'



  pull_request:
      branches:
        - 'aprendiendo-github-actions'
      types:
          - opened
          - synchronize
          - reopened

  schedule:
      - cron: '*/15 * * * *'